name: Cleanup AWS Resources

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: discord-pin-bot
  ECS_CLUSTER: discord-pin-bot-cluster
  ECS_SERVICE: discord-pin-bot-service

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Stop and remove ECS service
      run: |
        # Update service to 0 tasks
        aws ecs update-service \
          --cluster ${ECS_CLUSTER} \
          --service ${ECS_SERVICE} \
          --desired-count 0

        # Wait a bit for tasks to stop
        sleep 10

        # Delete service
        aws ecs delete-service \
          --cluster ${ECS_CLUSTER} \
          --service ${ECS_SERVICE} \
          --force

    - name: Delete ECS cluster
      run: |
        aws ecs delete-cluster --cluster ${ECS_CLUSTER}

    - name: Delete ECR repository
      run: |
        aws ecr delete-repository \
          --repository-name ${ECR_REPOSITORY} \
          --forceokay